config/routes.rb
Rails.application.routes.draw do

  	root 'welcome#index'
  	get 'notpaid', to: 'welcome#need_to_pay'
	resources :companies
	resources :users

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	resources :posts
	resources :searches

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :companies, dependent: :destroy
	

	before_save { self.email = email.downcase }

	validates :first_name, :last_name, presence: true, 
			   
	          length: {minimum: 3, maximum: 50}
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
			  uniqueness: {case_sensitive: false}, 
	          length: { maximum: 105},
	          format: { with: VALID_EMAIL_REGEX }

	has_secure_password

	def self.search(search)
	    users = all
	  if search
	    where('first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?',"%#{search}%", "%#{search}%", "%#{search}%")
	  else
	    all
	  end
	end

	def name
		"#{first_name} #{last_name}".titleize
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show, :destroy]
	skip_before_action :require_admin, only: [:show, :edit, :update]
	def index		
		@users = User.search(params[:search]).paginate(page: params[:page], per_page: 10).order(:last_name)
	end

	def new
		@user= User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save		  
		  flash[:notice] = "User added #{@user.name}"
		  redirect_to users_path
		else
		  render 'new'
		end
	end

	def update
		if @user.update(user_params)		  
		  flash[:notice] = "Profile of #{@user.name} was  updated"
		  redirect_to user_path(@user)
		else
		  render 'new'
		end
		
	end

	def show
		@users = User.all.order(:username)
		@company = Company.all
	end

	def edit
		
	end

	def destroy
		@user.destroy
		flash[:notice] = "User and all Companies deleted"
	    redirect_to users_path
		
	end


	private
	

	def set_user
		@user = User.find(params[:id])
	end
	
	def user_params
		# List of common params
        list_params_allowed =[:username, :first_name, :last_name, :email, :password, :password_confirmation]
        # Add the params only for admin
  		list_params_allowed << [:admin, :not_paid] if current_user.admin?
		params.require(:user).permit(list_params_allowed)
	end
 end

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="container">
	<div class="row center add-user-form">
		<div class="col s12 m12 l12">
			<div class="card-panel ">
				<h3 class="header"><%= @user.new_record? ? "Add user" : "Edit your profile" %></h3>
				<div class="row">        
					<%= form_for(@user, html: {class: "col s12" }) do |f| %>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :first_name, placeholder: "First Name", autofocus: true %>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :last_name, placeholder: "Last Name", autofocus: true %>
							</div>
						</div>

						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :username, placeholder: "Username", autofocus: true %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">	
								<%= f.email_field :email, placeholder: "Email Address" %>
							</div>
						</div>						
						<div class="row">
							<div class="input-field col s12">	
								<%= f.password_field :password, placeholder: "Choose a Password" %>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">	
								<%= f.password_field :pasword_confirmation, placeholder: "Confirm your Password" %>			
							</div>
						</div>
						<% if current_user.admin? %>
						<div class="row">
							<div class="input-field col s6">
								<label>	
									<%= f.check_box :admin %>
									<span>Admin?</span>
								</label>										
							</div>
							<div class="input-field col s6">
								<label>	
									<%= f.check_box :not_paid %>
									<span>Not paid?</span>
								</label>										
							</div>
						</div>
						<% end %>
						<div class="row">
							<div class="input-field col s12">
						<%= f.button(@user.new_record? ? '<i class="material-icons right">arrow_forward</i>Create User'.html_safe : '<i class="material-icons right">arrow_forward</i>Update profile'.html_safe, class: 'waves-effect waves-light btn-small') %>

							</div>
						</div>
					<% end %>
				</div>
				
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<%= render 'users/form'%>
<div class="center-align">
	<%= link_to '<i class="material-icons right">arrow_back</i>Back to profile'.html_safe, user_path(@user), class: 'waves-effect waves-light btn-small'  %>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="navbar-wrapper">	    
	    <form>
		    <%= form_tag users_path, method: :get do %>
				<div class="input-field col s10">		    
				    <%= text_field_tag :search, params[:search], type: 'search', placeholder: "            Search by first name, last name or email"  %>
				        <label class="label-icon" for="search"></label>
				        <i class="material-icons">search</i>      
				                 
				</div>
				<div class="input-field col s2">
				<%= submit_tag 'Search', class: 'waves-effect waves-light btn-small' %>
				</div>		    
			<% end %>
		</form>
	</div>
	<div class="col s12">
		<h3 class="center-align">All Users</h3><div><p><%= link_to "New User", new_user_path, class: 'waves-effect waves-light btn-small right' %></p></div>
	</div>
</div>

<table class="highlight">
	<thead>
	  <tr>
	      <th>First Name</th>
	      <th>Last Name</th>     
	      <th>Email</th>
	      <th colspan="3">Actions</th>
	  </tr>
	</thead>

	<tbody>

<% @users.each do |user| %>
      <tr>
	    <td><%= link_to user.first_name,  user_path(user) %></td>
	    <td><%= link_to user.last_name,  user_path(user) %></td>
	    <td><%= mail_to user.email, user.email, :subject => "You have new post!", :body =>"Hello #{user.username}, today #{Date.today.strftime("%d %b %Y")} you haved received new mail. Please login to see your post  https://ascherimailbox.herokuapp.com/".html_safe %></td>
	    <td><%= link_to '<i class="material-icons right">create</i>Edit profile'.html_safe, edit_user_path(user), class: 'waves-effect waves-light btn-small'  %></td>
	    <td><%= link_to '<i class="material-icons right">delete_forever</i>Delete'.html_safe, user_path(user), method: :delete, 
  					    data:{confirm: "Are you sure"}, class: 'waves-effect waves-light btn-small'  %></td>
	    
	  </tr>
<% end %>		
	</tbody>
</table>


<div class="center-align"><%= will_paginate @users %>  </div>

app/views/users/new.html.erb
<%= render 'users/form'%>
<div class="center-align">
	<%= link_to '<i class="material-icons right">arrow_back</i>Back to Users'.html_safe, users_path, class: 'waves-effect waves-light btn-small'  %>
</div>

app/views/users/show.html.erb
<div class="row add-user-form">
	<div class="col s12 m12 l12">
		<div class="card blue-grey lighten-2 ">
			<div class="card-content white-text">
				<span class="card-title">User Name: <%= @user.name %></span>
				<div class="col s6 m6 l6">
				   <p>Email: <%= @user.email %></p>
</div>
<div class="col s6 m6 l6">
				   <p>Companies</p>
				   <ul >
				   <% @user.companies.each do |user| %>

				   <li><%=link_to user.name, company_path(user), class: "btn-small" %></li><br>
				   <% end %>
				   </ul>
				</div>
				   <br>
				<div class="card-actions">
					<% if current_user.admin? %>
					<%= link_to '<i class="material-icons right">arrow_back</i>Back to All Users'.html_safe, users_path, class: 'waves-effect waves-light btn-small'  %>
					<% else %>
					<%= link_to '<i class="material-icons right">arrow_back</i>Back'.html_safe, companies_path, class: 'waves-effect waves-light btn-small'  %>			
					<% end %>
					<% if current_user == @user || current_user.admin? %>
					<%= link_to '<i class="material-icons right">create</i>Edit profile'.html_safe, edit_user_path(@user), class: 'waves-effect waves-light btn-small right'  %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>