config/routes.rb
Rails.application.routes.draw do

  	root 'welcome#index'
  	get 'notpaid', to: 'welcome#need_to_pay'
	resources :companies
	resources :users

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	resources :posts
	resources :searches

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :posts, dependent: :destroy
	belongs_to :user
	
	validates :name, presence: true,
			  uniqueness: {case_sensitive: false}

	def self.search(search)
	    companies = all
	  if search
	    where('name ILIKE ?', "%#{search}%")
	  else
	    all
	  end
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :set_company, only: [:edit, :update, :show, :destroy]
	skip_before_action :require_admin, only: [:index, :show]

	def index
		if current_user.admin?
			@companies = Company.search(params[:search]).paginate(page: params[:page], per_page: 10).order(:name)
		else
			@companies = current_user.companies
		end
		
	end

	def new
		@company= Company.new
	end

	def create
		@company = Company.new(company_params)
		if @company.save		  
		  flash[:notice] = "#{@company.name} added "
		  redirect_to companies_path
		else
		  render 'new'
		end
	end

	def update
		if @company.update(company_params)		  
		  flash[:notice] = "Profile of #{@company.name} was  updated"
		  redirect_to company_path(@company)
		else
		  render 'new'
		end
		
	end

	def show
		
	end

	def edit
		
	end

	def destroy
		@company.destroy
		flash[:notice] = "Company and all dependencies deleted"
	    redirect_to companies_path
		
	end

	private

	def set_company
		@company = Company.find(params[:id])
	end
	
	def company_params
		params.require(:company).permit(:name, :user_id)
	end


end

app/views/companies/_form.html.erb
<%= render 'shared/errors', obj: @company %>
<div class="container">
	<div class="row center add-user-form">
		<div class="col s12 m12 l12">
			<div class="card-panel ">
				<h3 class="header"><%= @company.new_record? ? "Add Company" : "Edit Company" %></h3>
				<div class="row">        
					<%= form_for(@company, html: {class: "col s12" }) do |f| %>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :name, placeholder: "Company Name", autofocus: true %>
								
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">	
								<%= f.collection_select :user_id, User.order(:first_name), :id, :name, { prompt: "Select User Name"} %>								
							</div>
						</div>

						<div class="row">
							<div class="input-field col s12">
						<%= f.button( @company.new_record? ? 
						'<i class="material-icons right">arrow_forward</i>Create Company'.html_safe : '<i class="material-icons right">arrow_forward</i>Update Company'.html_safe, class: 'waves-effect waves-light btn-small') %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/companies/edit.html.erb
<%= render 'companies/form' %>
<div class="center-align">
	<%= link_to '<i class="material-icons right">arrow_back</i>Back to Company'.html_safe, company_path(@company), class: 'waves-effect waves-light btn-small'  %>
</div>

app/views/companies/index.html.erb
<div class="row">
	<% if current_user.admin? %>
	<div class="navbar-wrapper">
	    <form>
		    <%= form_tag companies_path, method: :get do %>
				<div class="input-field col s10">
				    <%= text_field_tag :search, params[:search], type: 'search', placeholder: "            Search by company name"  %>
				        <label class="label-icon" for="search"></label>
				        <i class="material-icons">search</i>

				</div>
				<div class="input-field col s2">
				<%= submit_tag 'Search', class: 'waves-effect waves-light btn-small' %>
				</div>
			<% end %>
		</form>
	</div>
	<% end %>
	<div class="col s12">
		<h3 class="center-align">All Companies</h3>
		<% if current_user.admin? %>
		<div><%= link_to "New Company", new_company_path, class: 'waves-effect waves-light btn-small right' %></div>
		</div>
		<% end %>
	</div>


<table class="highlight">
	<thead>
	  <tr>
	      <th>Name</th>
	      <th>Username</th>
	      <th>Mail</th>
	      <% if current_user.admin? %>
	      <th colspan="2">Actions</th>
	       <% end %>
	  </tr>
	</thead>

	<tbody>
		<% @companies.each do |company|%>
	  <tr>
	    <td><%= link_to company.name, company_path(company) %></td>
	    <td><%= link_to company.user.name, user_path(company.user) %></td>
	    <td><%= link_to company.posts.name, posts_path %></td>
	    <% if current_user.admin? %>
	    <td><%= link_to '<i class="material-icons right ">create</i>Edit Company'.html_safe, edit_company_path(company), class: 'waves-effect waves-light btn-small'  %></td>
	    <td><%= link_to '<i class="material-icons right">delete_forever</i>Delete'.html_safe, company_path(company), method: :delete,
  					    data:{confirm: "Are you sure"}, class: 'waves-effect waves-light btn-small'  %></td>
  					    <% end %>
	  </tr>
	  <% end %>
	</tbody>
</table>
<% if current_user.admin? %>
<div class="center-align"><%= will_paginate @companies %>  </div>
<% end %>

app/views/companies/new.html.erb
<%= render 'companies/form'%>
<div class="center-align">
	<%= link_to '<i class="material-icons right">arrow_back</i>Back to Companies'.html_safe, companies_path, class: 'waves-effect waves-light btn-small'  %>
</div>

app/views/companies/show.html.erb
<div class="row add-user-form">
	<div class="col s12 m12 l12">
		<div class="card blue-grey lighten-2 ">
			<div class="card-content white-text">
				<span class="card-title">Company Name: <%= @company.name %></span>
				   <p>Contact: <%= @company.user.name %></p>
				   <br>
				<div class="card-actions">
					<%= link_to '<i class="material-icons right">arrow_back</i>Back'.html_safe, companies_path, class: 'waves-effect waves-light  btn-small'  %>		
					<%= link_to '<i class="material-icons right">create</i>Edit profile'.html_safe, edit_company_path(@company), class: 'waves-effect waves-light btn-small right'  %>
				</div>
			</div>
		</div>
	</div>
</div>