config/routes.rb
Rails.application.routes.draw do

  	root 'welcome#index'
  	get 'notpaid', to: 'welcome#need_to_pay'
	resources :companies
	resources :users

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	resources :posts
	resources :searches

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :company
	

   mount_uploader :attachment, AttachmentUploader 
   validates :name, presence: true
   validates :sender, presence: true
   validates :received, presence: true

    def self.search(search)
	    posts = all
	  if search
	    where('name ILIKE ? OR sender ILIKE ? OR cast(received as text) ILIKE ?',"%#{search}%", "%#{search}%", "%#{search}%")
	  else
	    all
	  end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  skip_before_action :require_admin, only: [:index, :show]

  def index
    
  	if current_user.admin?

      @posts = Post.paginate(page: params[:page], per_page: 10).order(created_at: :DESC)
    else
      @posts = Post.search(params[:search]).where(company_id: current_user.companies).paginate(page: params[:page], per_page: 10).order('received DESC')
    end
  end
   
   def new
      @post = Post.new
   end
   
   def create
      @post = Post.new(post_params)
      
      if @post.save
      	flash[:notice] = "The #{@post.name} has been uploaded."
         redirect_to posts_path
      else
         render "new"
      end
      
   end

   def edit
     
   end

   def show
     
   end

   def update
    if @post.update(post_params)      
      flash[:notice] = "The#{@post.name} was  updated"
      redirect_to posts_path
    else
      render 'new'
    end
    
  end
   
   def destroy
      
      @post.destroy
      flash[:notice] = "The resume #{@post.name} has been deleted."
      redirect_to posts_path  
   end
   
   private

    def set_post
      @post = Post.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:name, :attachment, :sender, :received, :company_id, :search)
    end
   
end

app/views/posts/_post.html.erb
	  <tr>
	    <td><%= post.company.name %></td>
	    <td><%= post.sender %></td>
	    <td><%= post.name %></td>
	    <td><%= post.received %></td>
	    <td><%= link_to "View or Download", post.attachment_url %></td>
	    <% if current_user.admin? %>
	    <td><%= mail_to post.company.user.email, post.company.user.email, :subject => "Nuova corrispondenza!", :body =>"Buongiorno #{post.company.user.name},

Oggi #{Date.today.strftime("%d %b %Y")} e’ stata caricata la nuova corrispondenza ricevuta dalla società #{post.company.name} .

Di seguito il link per effettuare l'accesso  https://ascherimailbox.herokuapp.com/" %></td>
	    <td><%= link_to '<i class="material-icons right">create</i>Edit'.html_safe, edit_post_path(post),
	        class: 'waves-effect waves-light btn-small'  %></td>
	        <td><%= link_to '<i class="material-icons right">delete_forever</i>Delete'.html_safe, post_path(post), method: :delete, data:{confirm: "Are you sure"},
	        class: 'waves-effect waves-light btn-small'  %></td>
  		<% end %>
	  </tr>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row center add-user-form">
		<div class="col s12 m12 l12">
			<div class="card-panel ">
				<h3 class="header">New mail</h3>
				<div class="row">        
					<%= form_for(@post, html: {class: "col s12"}) do |f| %>
						<div class="row">
							<div class="input-field col s12">	
								<%= f.collection_select :company_id, Company.all, :id, :name, { prompt: "Select Company"} %>								
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :name, placeholder: "Mail Name" %>		
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :sender, placeholder: "Sender"%>				
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.date_field :received, placeholder: "Sender"%>				
							</div>
						</div>
						<div class="row">
							<div class="file-field input-field">
						      <div class="btn">
						        <span>File</span>
						        <%= f.file_field :attachment, placeholder: "Upload one or more files", class: "file-path validate" %>
						      </div>
						      <div class="file-path-wrapper">
						        <input class="file-path validate" type="text" placeholder="Upload one or more files">
						      </div>
							</div>
					    </div>
										
						<div class="row">
							<div class="input-field col s12">
						      <%= f.button '<i class="material-icons right">arrow_forward</i>Upload'.html_safe, class: 'waves-effect waves-light btn-small'%>
							</div>
						</div>
					<% end %>
					
				</div>
			</div>
		</div>
    </div>
</div>


    

app/views/posts/index.html.erb
<div class="row">
	<div class="navbar-wrapper">
	<% if current_user.admin? %>

	<% else %>
	    <form>
		    <%= form_tag posts_path, method: :get do %>
				<div class="input-field col s10">
				    <%= text_field_tag :search, params[:search], type: 'search', placeholder: "            Search for mail by name or sender "  %>
				        <label class="label-icon" for="search"></label>
				        <i class="material-icons">search</i>

				</div>
				<div class="input-field col s2">
				<%= submit_tag 'Search', class: 'waves-effect waves-light btn-small' %>
				</div>

			<% end %>
		</form>
	<% end %>
	</div>

	<div class="col s12">
		<h3 class="center-align">All Mails</h3>
			<div class="col s6"> <%= link_to '<i class="material-icons right">arrow_back</i>Back'.html_safe, companies_path, class: 'waves-effect waves-light btn-small'  %>
			</div>
		<% if current_user.admin? %>
			<div class="col s6"><%= link_to "Upload Mail", new_post_path, class: 'waves-effect waves-light btn-small right' %>
			</div>
		<% end %>
	</div>
</div>
<% if current_user.admin? %>
<div class="row">
	<div class="col s12 center-align"><%= link_to "Advance search", new_search_path, class: 'waves-effect waves-light btn-small'%></div>
</div>
	<% end %>

	<div class="center-align">

<h5 class="blue-text"> - <%= pluralize(@posts.count, "mail")  %> - </h5>

</div>

<table class="highlight">
	<thead>
	  <tr>
	  	  <th>Company</th>
	      <th>Sender</th>
	      <th>Name</th>
	      <th>Received on</th>
	      <% if current_user.admin? %>

	      <th>Email User</th>
	      <% end %>
	      <th>View Mail</th>
	      <% if current_user.admin? %>


	      <th colspan="2">Actions</th>
	      <% end %>
	  </tr>
	</thead>

	<tbody>
		<% @posts.each do |post|%>
	  <tr>
	    <td><%= post.company.name %></td>
	    <td><%= post.sender %></td>
	    <td><%= post.name %></td>
	    <td><%= post.received %></td>
	    <% if current_user.admin? %>
	    <td><%= mail_to post.company.user.email, post.company.user.email, :subject => "Nuova corrispondenza per #{post.company.name}!", :body =>"Buongiorno #{post.company.user.name},

Oggi #{Date.today.strftime("%d %b %Y")} e’ stata caricata la nuova corrispondenza ricevuta dalla società #{post.company.name} .

Di seguito il link per effettuare l'accesso  https://ascherimailbox.herokuapp.com/".html_safe %></td>
	    <% end %>
	    <td><%= link_to "View or Download", post.attachment_url %></td>
	    <% if current_user.admin? %>

	    <td><%= link_to '<i class="material-icons right">create</i>Edit'.html_safe, edit_post_path(post),
	        class: 'waves-effect waves-light btn-small'  %></td>
	        <td><%= link_to '<i class="material-icons right">delete_forever</i>Delete'.html_safe, post_path(post), method: :delete, data:{confirm: "Are you sure"},
	        class: 'waves-effect waves-light btn-small'  %></td>
  		<% end %>
	  </tr>
	  <% end %>
	</tbody>
</table>


  <div class="center-align"><%= will_paginate @posts %>  </div>

app/views/posts/new.html.erb
<%= render 'shared/errors', obj: @post %>
<div class="container">
	<div class="row center add-user-form">
		<div class="col s12 m12 l12">
			<div class="card-panel ">
				<h3 class="header">New mail</h3>
				<div class="row">        
					<%= form_for(@post, html: {class: "col s12", multipart: true }) do |f| %>
						<div class="row">
							<div class="input-field col s12">	
								<%= f.collection_select :company_id, Company.all, :id, :name, { prompt: "Select Company"} %>								
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :name, placeholder: "Mail Name" %>		
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :sender, placeholder: "Sender"%>				
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.date_field :received, placeholder: "Sender"%>				
							</div>
						</div>
						<div class="row">
							<div class="file-field input-field">
					      <div class="btn">
					        <span>File</span>
					        <%= f.file_field :attachment, placeholder: "Upload one or more files", class: "file-path validate" %>
					      </div>
					      <div class="file-path-wrapper">
					        <input class="file-path validate" type="text" placeholder="Upload one or more files">
					      </div>
					  </div>
						
						<div class="row">
							<div class="input-field col s12">
						      <%= f.button '<i class="material-icons right">arrow_forward</i>Upload'.html_safe, class: 'waves-effect waves-light btn-small'%>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>


    