config/routes.rb
Rails.application.routes.draw do

  	root 'welcome#index'
  	get 'notpaid', to: 'welcome#need_to_pay'
	resources :companies
	resources :users

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	resources :posts
	resources :searches

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flashmsg.html.erb
<% flash.each do |key, message| %>
	<div class="container">
		<div class="row add-user-form">
			<div class="col s12 m12 l12">
				<div class="card-panel red lighten-2 " id= "fade-out-target">
					<span class="white-text">
						<%= message %>
					</span>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer blue darken-3">
    <div class="footer-copyright">
	    <div class="container">
	    © 2019 Copyright 
		    <a class="grey-text text-lighten-4 right" href="http://www.ascheri.co.uk">Ascheri & Partners</a>
	    </div>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
	<nav class="nav blue darken-3">
		<div class="container">
		    <div class="nav-wrapper">
		      <%= link_to "Ascheri Mailbox", companies_path, class: "brand-logo" %>
		      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
		      <ul id="nav-mobile" class="right hide-on-med-and-down">
		        <% if current_user.admin? %>
		        	<li><%= link_to "Companies", companies_path %></li>
		        	<li><%= link_to "Post", posts_path %></li>
		        	<li><%= link_to "Users", users_path %></li>
		        <% end %>
		        <li><%= link_to current_user.name, user_path(current_user) %></li>
		        <% if (logged_in?) %>
		        <li><%= link_to "Logout", logout_path, method: :delete %></li>
		        <% end %>
		      </ul>
		    </div>
	    </div>
	  </nav>

	  <ul class="sidenav" id="mobile-demo">
	  	<li><%= link_to current_user.name, user_path(current_user) %></li>
	    <% if (logged_in?) %>
		    <li><%= link_to "Logout", logout_path, method: :delete %></li>
		<% end %>
	  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mailbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  	
	  	<% unless controller_name == 'welcome' || controller_name == 'sessions' %>
	  	  <%= render 'layouts/navbar' %>
	  	<% end %>  	
  	<main>  			      
	  	<div class="container">
	  		
	  		<%= render 'layouts/flashmsg' %>
	      <%= yield %>
		</div>
	</main>
	
	<% unless controller_name == 'welcome' || controller_name == 'sessions' %>
	  <%= render 'layouts/footer' %>
	<% end %>
  </body>
</html>